package com.example.demo.errcode;

public enum ApiErrCode {
	SAVE_SUCCESS,
	CONNECT_ERROR,
	BILL_CONFIRMED_SUCCESS,
	BILL_CONFIRMED_FAIL,
	BILL_COMPLETED_DELIVERING,
	BILL_FAIL_TO_DELIVERY,
	BILL_CANCELED_SUCCESS,
	BILL_CANCLED_FAIL,
	BILL_PROCESSED_SUCCESS,
	BILL_PROCESSED_FAIL
}
