package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Binhluan generated by hbm2java
 */
@Entity
@Table(name = "binhluan")
public class Binhluan implements java.io.Serializable {

	private BinhluanId id;
	private Mathang mathang;
	private Taikhoan taikhoan;
	private String noidung;

	public Binhluan() {
	}

	public Binhluan(BinhluanId id, Mathang mathang, Taikhoan taikhoan) {
		this.id = id;
		this.mathang = mathang;
		this.taikhoan = taikhoan;
	}

	public Binhluan(BinhluanId id, Mathang mathang, Taikhoan taikhoan, String noidung) {
		this.id = id;
		this.mathang = mathang;
		this.taikhoan = taikhoan;
		this.noidung = noidung;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ngaybl", column = @Column(name = "NGAYBL", nullable = false, length = 10)),
			@AttributeOverride(name = "matk", column = @Column(name = "MATK", nullable = false)),
			@AttributeOverride(name = "mamh", column = @Column(name = "MAMH", nullable = false)) })
	public BinhluanId getId() {
		return this.id;
	}

	public void setId(BinhluanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAMH", nullable = false, insertable = false, updatable = false)
	public Mathang getMathang() {
		return this.mathang;
	}

	public void setMathang(Mathang mathang) {
		this.mathang = mathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATK", nullable = false, insertable = false, updatable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "NOIDUNG", length = 200)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

}
