package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BinhluanId generated by hbm2java
 */
@Embeddable
public class BinhluanId implements java.io.Serializable {

	private Date ngaybl;
	private int matk;
	private int mamh;

	public BinhluanId() {
	}

	public BinhluanId(Date ngaybl, int matk, int mamh) {
		this.ngaybl = ngaybl;
		this.matk = matk;
		this.mamh = mamh;
	}

	@Column(name = "NGAYBL", nullable = false, length = 10)
	public Date getNgaybl() {
		return this.ngaybl;
	}

	public void setNgaybl(Date ngaybl) {
		this.ngaybl = ngaybl;
	}

	@Column(name = "MATK", nullable = false)
	public int getMatk() {
		return this.matk;
	}

	public void setMatk(int matk) {
		this.matk = matk;
	}

	@Column(name = "MAMH", nullable = false)
	public int getMamh() {
		return this.mamh;
	}

	public void setMamh(int mamh) {
		this.mamh = mamh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BinhluanId))
			return false;
		BinhluanId castOther = (BinhluanId) other;

		return ((this.getNgaybl() == castOther.getNgaybl()) || (this.getNgaybl() != null
				&& castOther.getNgaybl() != null && this.getNgaybl().equals(castOther.getNgaybl())))
				&& (this.getMatk() == castOther.getMatk()) && (this.getMamh() == castOther.getMamh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNgaybl() == null ? 0 : this.getNgaybl().hashCode());
		result = 37 * result + this.getMatk();
		result = 37 * result + this.getMamh();
		return result;
	}

}
