package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtHoadonId generated by hbm2java
 */
@Embeddable
public class CtHoadonId implements java.io.Serializable {

	private int mahd;
	private int id;

	public CtHoadonId() {
	}

	public CtHoadonId(int mahd, int id) {
		this.mahd = mahd;
		this.id = id;
	}

	@Column(name = "MAHD", nullable = false)
	public int getMahd() {
		return this.mahd;
	}

	public void setMahd(int mahd) {
		this.mahd = mahd;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtHoadonId))
			return false;
		CtHoadonId castOther = (CtHoadonId) other;

		return (this.getMahd() == castOther.getMahd()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMahd();
		result = 37 * result + this.getId();
		return result;
	}

}
