package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtHoadon generated by hbm2java
 */
@Entity
@Table(name = "ct_hoadon")
public class CtHoadon implements java.io.Serializable {

	private CtHoadonId id;
	private CtMathang ctMathang;
	private Hoadon hoadon;
	private Integer soluong;
	private Integer gia;

	public CtHoadon() {
	}

	public CtHoadon(CtHoadonId id, CtMathang ctMathang, Hoadon hoadon) {
		this.id = id;
		this.ctMathang = ctMathang;
		this.hoadon = hoadon;
	}

	public CtHoadon(CtHoadonId id, CtMathang ctMathang, Hoadon hoadon, Integer soluong, Integer gia) {
		this.id = id;
		this.ctMathang = ctMathang;
		this.hoadon = hoadon;
		this.soluong = soluong;
		this.gia = gia;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mahd", column = @Column(name = "MAHD", nullable = false)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)) })
	public CtHoadonId getId() {
		return this.id;
	}

	public void setId(CtHoadonId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID", nullable = false, insertable = false, updatable = false)
	public CtMathang getCtMathang() {
		return this.ctMathang;
	}

	public void setCtMathang(CtMathang ctMathang) {
		this.ctMathang = ctMathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAHD", nullable = false, insertable = false, updatable = false)
	public Hoadon getHoadon() {
		return this.hoadon;
	}

	public void setHoadon(Hoadon hoadon) {
		this.hoadon = hoadon;
	}

	@Column(name = "SOLUONG")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	@Column(name = "GIA")
	public Integer getGia() {
		return this.gia;
	}

	public void setGia(Integer gia) {
		this.gia = gia;
	}

}
