package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtKhuyenmaiId generated by hbm2java
 */
@Embeddable
public class CtKhuyenmaiId implements java.io.Serializable {

	private int makm;
	private int mamh;

	public CtKhuyenmaiId() {
	}

	public CtKhuyenmaiId(int makm, int mamh) {
		this.makm = makm;
		this.mamh = mamh;
	}

	@Column(name = "MAKM", nullable = false)
	public int getMakm() {
		return this.makm;
	}

	public void setMakm(int makm) {
		this.makm = makm;
	}

	@Column(name = "MAMH", nullable = false)
	public int getMamh() {
		return this.mamh;
	}

	public void setMamh(int mamh) {
		this.mamh = mamh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtKhuyenmaiId))
			return false;
		CtKhuyenmaiId castOther = (CtKhuyenmaiId) other;

		return (this.getMakm() == castOther.getMakm()) && (this.getMamh() == castOther.getMamh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMakm();
		result = 37 * result + this.getMamh();
		return result;
	}

}
