package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.example.demo.entity.Color;
import com.example.demo.entity.Size;

/**
 * CtMathang generated by hbm2java
 */
@Entity
@Table(name = "ct_mathang")
public class CtMathang implements java.io.Serializable {

	private Integer id;
	private Mathang mathang;
	private Size size;
	private Color color;
	private String currentNumbeer;
	private Set<CtHoadon> ctHoadons = new HashSet<CtHoadon>(0);
	private Set<CtPhieudat> ctPhieudats = new HashSet<CtPhieudat>(0);
	private Set<CtPhieunhap> ctPhieunhaps = new HashSet<CtPhieunhap>(0);

	public CtMathang() {
	}

	public CtMathang(Integer id, Mathang mathang, Color color, Size size, String currentNumbeer) {
		super();
		this.id = id;
		this.mathang = mathang;
		this.color = color;
		this.size = size;
		this.currentNumbeer = currentNumbeer;
	}

	public CtMathang(Mathang mathang, Color color, Size size, String currentNumbeer, Set<CtHoadon> ctHoadons,
			Set<CtPhieudat> ctPhieudats, Set<CtPhieunhap> ctPhieunhaps) {
		this.mathang = mathang;
		this.color = color;
		this.size = size;
		this.currentNumbeer = currentNumbeer;
		this.ctHoadons = ctHoadons;
		this.ctPhieudats = ctPhieudats;
		this.ctPhieunhaps = ctPhieunhaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAMH")
	public Mathang getMathang() {
		return this.mathang;
	}

	public void setMathang(Mathang mathang) {
		this.mathang = mathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MACOLOR")
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MASIZE")
	public Size getSize() {
		return this.size;
	}

	public void setSize(Size size) {
		this.size = size;
	}

	@Column(name = "CURRENT_NUMBEER", length = 45)
	public String getCurrentNumbeer() {
		return this.currentNumbeer;
	}

	public void setCurrentNumbeer(String currentNumbeer) {
		this.currentNumbeer = currentNumbeer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ctMathang")
	public Set<CtHoadon> getCtHoadons() {
		return this.ctHoadons;
	}

	public void setCtHoadons(Set<CtHoadon> ctHoadons) {
		this.ctHoadons = ctHoadons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ctMathang")
	public Set<CtPhieudat> getCtPhieudats() {
		return this.ctPhieudats;
	}

	public void setCtPhieudats(Set<CtPhieudat> ctPhieudats) {
		this.ctPhieudats = ctPhieudats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ctMathang")
	public Set<CtPhieunhap> getCtPhieunhaps() {
		return this.ctPhieunhaps;
	}

	public void setCtPhieunhaps(Set<CtPhieunhap> ctPhieunhaps) {
		this.ctPhieunhaps = ctPhieunhaps;
	}

}
