package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtPhieudat generated by hbm2java
 */
@Entity
@Table(name = "ct_phieudat")
public class CtPhieudat implements java.io.Serializable {

	private CtPhieudatId id;
	private CtMathang ctMathang;
	private Phieudat phieudat;
	private String soluong;
	private String dongia;

	public CtPhieudat() {
	}

	public CtPhieudat(CtMathang ctMathang, String soluong, String dongia) {
		super();
		this.ctMathang = ctMathang;
		this.soluong = soluong;
		this.dongia = dongia;
	}

	public CtPhieudat(CtPhieudatId id, CtMathang ctMathang, Phieudat phieudat) {
		this.id = id;
		this.ctMathang = ctMathang;
		this.phieudat = phieudat;
	}

	public CtPhieudat(CtPhieudatId id, CtMathang ctMathang, String soluong, String dongia) {
		super();
		this.id = id;
		this.ctMathang = ctMathang;
		this.soluong = soluong;
		this.dongia = dongia;
	}

	public CtPhieudat(CtPhieudatId id, CtMathang ctMathang, Phieudat phieudat, String soluong, String dongia) {
		this.id = id;
		this.ctMathang = ctMathang;
		this.phieudat = phieudat;
		this.soluong = soluong;
		this.dongia = dongia;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "mapd", column = @Column(name = "MAPD", nullable = false)) })
	public CtPhieudatId getId() {
		return this.id;
	}

	public void setId(CtPhieudatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID", nullable = false, insertable = false, updatable = false)
	public CtMathang getCtMathang() {
		return this.ctMathang;
	}

	public void setCtMathang(CtMathang ctMathang) {
		this.ctMathang = ctMathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAPD", nullable = false, insertable = false, updatable = false)
	public Phieudat getPhieudat() {
		return this.phieudat;
	}

	public void setPhieudat(Phieudat phieudat) {
		this.phieudat = phieudat;
	}

	@Column(name = "SOLUONG", length = 45)
	public String getSoluong() {
		return this.soluong;
	}

	public void setSoluong(String soluong) {
		this.soluong = soluong;
	}

	@Column(name = "DONGIA", length = 45)
	public String getDongia() {
		return this.dongia;
	}

	public void setDongia(String dongia) {
		this.dongia = dongia;
	}

}
