package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtPhieudatId generated by hbm2java
 */
@Embeddable
public class CtPhieudatId implements java.io.Serializable {

	private int id;
	private int mapd;

	public CtPhieudatId() {
	}

	public CtPhieudatId(int id, int mapd) {
		this.id = id;
		this.mapd = mapd;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MAPD", nullable = false)
	public int getMapd() {
		return this.mapd;
	}

	public void setMapd(int mapd) {
		this.mapd = mapd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtPhieudatId))
			return false;
		CtPhieudatId castOther = (CtPhieudatId) other;

		return (this.getId() == castOther.getId()) && (this.getMapd() == castOther.getMapd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getMapd();
		return result;
	}

}
