package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtPhieunhap generated by hbm2java
 */
@Entity
@Table(name = "ct_phieunhap")
public class CtPhieunhap implements java.io.Serializable {

	private CtPhieunhapId id;
	private CtMathang ctMathang;
	private Phieunhap phieunhap;
	private Integer soluong;
	private Integer dongia;

	public CtPhieunhap() {
	}

	public CtPhieunhap(CtPhieunhapId id, CtMathang ctMathang, Integer soluong, Integer dongia) {
		super();
		this.id = id;
		this.ctMathang = ctMathang;
		this.soluong = soluong;
		this.dongia = dongia;
	}

	public CtPhieunhap(CtPhieunhapId id, CtMathang ctMathang, Phieunhap phieunhap) {
		this.id = id;
		this.ctMathang = ctMathang;
		this.phieunhap = phieunhap;
	}

	public CtPhieunhap(CtPhieunhapId id, CtMathang ctMathang, Phieunhap phieunhap, Integer soluong, Integer dongia) {
		this.id = id;
		this.ctMathang = ctMathang;
		this.phieunhap = phieunhap;
		this.soluong = soluong;
		this.dongia = dongia;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mapn", column = @Column(name = "MAPN", nullable = false)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)) })
	public CtPhieunhapId getId() {
		return this.id;
	}

	public void setId(CtPhieunhapId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID", nullable = false, insertable = false, updatable = false)
	public CtMathang getCtMathang() {
		return this.ctMathang;
	}

	public void setCtMathang(CtMathang ctMathang) {
		this.ctMathang = ctMathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAPN", nullable = false, insertable = false, updatable = false)
	public Phieunhap getPhieunhap() {
		return this.phieunhap;
	}

	public void setPhieunhap(Phieunhap phieunhap) {
		this.phieunhap = phieunhap;
	}

	@Column(name = "SOLUONG")
	public Integer getSoluong() {
		return this.soluong;
	}

	public void setSoluong(Integer soluong) {
		this.soluong = soluong;
	}

	@Column(name = "DONGIA")
	public Integer getDongia() {
		return this.dongia;
	}

	public void setDongia(Integer dongia) {
		this.dongia = dongia;
	}

}
