package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtPhieunhapId generated by hbm2java
 */
@Embeddable
public class CtPhieunhapId implements java.io.Serializable {

	private int mapn;
	private int id;

	public CtPhieunhapId() {
	}

	public CtPhieunhapId(int mapn, int id) {
		this.mapn = mapn;
		this.id = id;
	}

	@Column(name = "MAPN", nullable = false)
	public int getMapn() {
		return this.mapn;
	}

	public void setMapn(int mapn) {
		this.mapn = mapn;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtPhieunhapId))
			return false;
		CtPhieunhapId castOther = (CtPhieunhapId) other;

		return (this.getMapn() == castOther.getMapn()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMapn();
		result = 37 * result + this.getId();
		return result;
	}

}
