package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtQuyenId generated by hbm2java
 */
@Embeddable
public class CtQuyenId implements java.io.Serializable {

	private Date ngaystart;
	private int maquyen;
	private int matk;

	public CtQuyenId() {
	}

	public CtQuyenId(Date ngaystart, int maquyen, int matk) {
		this.ngaystart = ngaystart;
		this.maquyen = maquyen;
		this.matk = matk;
	}

	@Column(name = "NGAYSTART", nullable = false, length = 10)
	public Date getNgaystart() {
		return this.ngaystart;
	}

	public void setNgaystart(Date ngaystart) {
		this.ngaystart = ngaystart;
	}

	@Column(name = "MAQUYEN", nullable = false)
	public int getMaquyen() {
		return this.maquyen;
	}

	public void setMaquyen(int maquyen) {
		this.maquyen = maquyen;
	}

	@Column(name = "MATK", nullable = false)
	public int getMatk() {
		return this.matk;
	}

	public void setMatk(int matk) {
		this.matk = matk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtQuyenId))
			return false;
		CtQuyenId castOther = (CtQuyenId) other;

		return ((this.getNgaystart() == castOther.getNgaystart()) || (this.getNgaystart() != null
				&& castOther.getNgaystart() != null && this.getNgaystart().equals(castOther.getNgaystart())))
				&& (this.getMaquyen() == castOther.getMaquyen()) && (this.getMatk() == castOther.getMatk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNgaystart() == null ? 0 : this.getNgaystart().hashCode());
		result = 37 * result + this.getMaquyen();
		result = 37 * result + this.getMatk();
		return result;
	}

}
