package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CtTrangthai generated by hbm2java
 */
@Entity
@Table(name = "ct_trangthai")
public class CtTrangthai implements java.io.Serializable {
	private CtTrangthaiId id;
	private Hoadon hoadon;
	private Trangthaihd trangthaihd;
	private Date ngaytao;

	public CtTrangthai() {
	}

	public CtTrangthai(CtTrangthaiId id, Hoadon hoadon, Trangthaihd trangthaihd) {
		this.id = id;
		this.hoadon = hoadon;
		this.trangthaihd = trangthaihd;
	}

	public CtTrangthai(CtTrangthaiId id, Hoadon hoadon, Trangthaihd trangthaihd, Date ngaytao) {
		this.id = id;
		this.hoadon = hoadon;
		this.trangthaihd = trangthaihd;
		this.ngaytao = ngaytao;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "mahd", column = @Column(name = "MAHD", nullable = false)),
			@AttributeOverride(name = "matthd", column = @Column(name = "MATTHD", nullable = false)) })
	public CtTrangthaiId getId() {
		return this.id;
	}

	public void setId(CtTrangthaiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MAHD", nullable = false, insertable = false, updatable = false)
	public Hoadon getHoadon() {
		return this.hoadon;
	}

	public void setHoadon(Hoadon hoadon) {
		this.hoadon = hoadon;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MATTHD", nullable = false, insertable = false, updatable = false)
	public Trangthaihd getTrangthaihd() {
		return this.trangthaihd;
	}

	public void setTrangthaihd(Trangthaihd trangthaihd) {
		this.trangthaihd = trangthaihd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYTAO", length = 10)
	public Date getNgaytao() {
		return this.ngaytao;
	}

	public void setNgaytao(Date ngaytao) {
		this.ngaytao = ngaytao;
	}

}
