package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Danhgia generated by hbm2java
 */
@Entity
@Table(name = "danhgia")
public class Danhgia implements java.io.Serializable {

	private DanhgiaId id;
	private Mathang mathang;
	private Taikhoan taikhoan;
	private Integer number;

	public Danhgia() {
	}

	public Danhgia(DanhgiaId id, Mathang mathang, Taikhoan taikhoan) {
		this.id = id;
		this.mathang = mathang;
		this.taikhoan = taikhoan;
	}

	public Danhgia(DanhgiaId id, Mathang mathang, Taikhoan taikhoan, Integer number) {
		this.id = id;
		this.mathang = mathang;
		this.taikhoan = taikhoan;
		this.number = number;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ngaydg", column = @Column(name = "NGAYDG", nullable = false, length = 10)),
			@AttributeOverride(name = "matk", column = @Column(name = "MATK", nullable = false)),
			@AttributeOverride(name = "mamh", column = @Column(name = "MAMH", nullable = false)) })
	public DanhgiaId getId() {
		return this.id;
	}

	public void setId(DanhgiaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAMH", nullable = false, insertable = false, updatable = false)
	public Mathang getMathang() {
		return this.mathang;
	}

	public void setMathang(Mathang mathang) {
		this.mathang = mathang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATK", nullable = false, insertable = false, updatable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "NUMBER")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

}
