package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GiaId generated by hbm2java
 */
@Embeddable
public class GiaId implements java.io.Serializable {

	private int mamh;
	private Date ngayapdung;
	private int manv;

	public GiaId() {
	}

	public GiaId(int mamh, Date ngayapdung, int manv) {
		this.mamh = mamh;
		this.ngayapdung = ngayapdung;
		this.manv = manv;
	}

	@Column(name = "MAMH", nullable = false)
	public int getMamh() {
		return this.mamh;
	}

	public void setMamh(int mamh) {
		this.mamh = mamh;
	}

	@Column(name = "NGAYAPDUNG", nullable = false, length = 10)
	public Date getNgayapdung() {
		return this.ngayapdung;
	}

	public void setNgayapdung(Date ngayapdung) {
		this.ngayapdung = ngayapdung;
	}

	@Column(name = "MANV", nullable = false)
	public int getManv() {
		return this.manv;
	}

	public void setManv(int manv) {
		this.manv = manv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GiaId))
			return false;
		GiaId castOther = (GiaId) other;

		return (this.getMamh() == castOther.getMamh())
				&& ((this.getNgayapdung() == castOther.getNgayapdung()) || (this.getNgayapdung() != null
						&& castOther.getNgayapdung() != null && this.getNgayapdung().equals(castOther.getNgayapdung())))
				&& (this.getManv() == castOther.getManv());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMamh();
		result = 37 * result + (getNgayapdung() == null ? 0 : this.getNgayapdung().hashCode());
		result = 37 * result + this.getManv();
		return result;
	}

}
