package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name = "hoadon")
public class Hoadon implements java.io.Serializable {

	private Integer mahd;
	private Khachhang khachhang;
	private Nhanvien nhanvien;
	private Date ngaytao;
	private Integer tongtien;
	private Shipper shipper;
	private Set<CtTrangthai> ctTrangthais = new HashSet<CtTrangthai>(0);
	private Set<CtHoadon> ctHoadons = new HashSet<CtHoadon>(0);

	public Hoadon() {
	}

	

	public Hoadon(Integer mahd, Khachhang khachhang, Nhanvien nhanvien, Date ngaytao, Integer tongtien, Shipper shipper,
			Set<CtTrangthai> ctTrangthais, Set<CtHoadon> ctHoadons) {
		super();
		this.mahd = mahd;
		this.khachhang = khachhang;
		this.nhanvien = nhanvien;
		this.ngaytao = ngaytao;
		this.tongtien = tongtien;
		this.shipper = shipper;
		this.ctTrangthais = ctTrangthais;
		this.ctHoadons = ctHoadons;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MAHD", unique = true, nullable = false)
	public Integer getMahd() {
		return this.mahd;
	}

	public void setMahd(Integer mahd) {
		this.mahd = mahd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKH")
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANV")
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYTAO", length = 10)
	public Date getNgaytao() {
		return this.ngaytao;
	}
	
	public void setNgaytao(Date ngaytao) {
		this.ngaytao = ngaytao;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MASHIPPER")
	public Shipper getShipper() {
		return shipper;
	}



	public void setShipper(Shipper shipper) {
		this.shipper = shipper;
	}



	@Column(name = "TONGTIEN")
	public Integer getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(Integer tongtien) {
		this.tongtien = tongtien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadon")
	public Set<CtTrangthai> getCtTrangthais() {
		return this.ctTrangthais;
	}

	public void setCtTrangthais(Set<CtTrangthai> ctTrangthais) {
		this.ctTrangthais = ctTrangthais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadon")
	public Set<CtHoadon> getCtHoadons() {
		return this.ctHoadons;
	}

	public void setCtHoadons(Set<CtHoadon> ctHoadons) {
		this.ctHoadons = ctHoadons;
	}

}
