package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Khachhang generated by hbm2java
 */
@Entity
@Table(name = "khachhang", uniqueConstraints = @UniqueConstraint(columnNames = "MATK"))
public class Khachhang implements java.io.Serializable {

	private Integer makh;
	private Taikhoan taikhoan;
	private String hotenkh;
	private String gioitinh;
	private Date ngaysinh;
	private String sdt;
	private String email;
	private String diachi;
	private String cmnd;
	private Set<Hoadon> hoadons = new HashSet<Hoadon>(0);
	private Set<Taikhoan> taikhoans = new HashSet<Taikhoan>(0);

	public Khachhang() {
	}

	public Khachhang(Taikhoan taikhoan, String hotenkh, String gioitinh, Date ngaysinh, String sdt, String email,
			String diachi, String cmnd, Set<Hoadon> hoadons, Set<Taikhoan> taikhoans) {
		this.taikhoan = taikhoan;
		this.hotenkh = hotenkh;
		this.gioitinh = gioitinh;
		this.ngaysinh = ngaysinh;
		this.sdt = sdt;
		this.email = email;
		this.diachi = diachi;
		this.cmnd = cmnd;
		this.hoadons = hoadons;
		this.taikhoans = taikhoans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAKH", unique = true, nullable = false)
	public Integer getMakh() {
		return this.makh;
	}

	public void setMakh(Integer makh) {
		this.makh = makh;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MATK", unique = true)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "HOTENKH", length = 45)
	public String getHotenkh() {
		return this.hotenkh;
	}

	public void setHotenkh(String hotenkh) {
		this.hotenkh = hotenkh;
	}

	@Column(name = "GIOITINH", length = 45)
	public String getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(String gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYSINH", length = 10)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "SDT", length = 45)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "DIACHI", length = 45)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "CMND", length = 45)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "khachhang")
	public Set<Hoadon> getHoadons() {
		return this.hoadons;
	}

	public void setHoadons(Set<Hoadon> hoadons) {
		this.hoadons = hoadons;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "khachhang")
	public Set<Taikhoan> getTaikhoans() {
		return this.taikhoans;
	}

	public void setTaikhoans(Set<Taikhoan> taikhoans) {
		this.taikhoans = taikhoans;
	}

}
