package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Loaimh generated by hbm2java
 */
@Entity
@Table(name = "loaimh", uniqueConstraints = @UniqueConstraint(columnNames = "TENLOADIMH"))
public class Loaimh implements java.io.Serializable {

	private Integer maloaimh;
	private String tenloadimh;
	private Set<Mathang> mathangs = new HashSet<Mathang>(0);

	public Loaimh() {
	}

	public Loaimh(String tenloadimh) {
		this.tenloadimh = tenloadimh;
	}

	public Loaimh(String tenloadimh, Set<Mathang> mathangs) {
		this.tenloadimh = tenloadimh;
		this.mathangs = mathangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MALOAIMH", unique = true, nullable = false)
	public Integer getMaloaimh() {
		return this.maloaimh;
	}

	public void setMaloaimh(Integer maloaimh) {
		this.maloaimh = maloaimh;
	}

	@Column(name = "TENLOADIMH", unique = true, nullable = false, length = 45)
	public String getTenloadimh() {
		return this.tenloadimh;
	}

	public void setTenloadimh(String tenloadimh) {
		this.tenloadimh = tenloadimh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaimh")
	public Set<Mathang> getMathangs() {
		return this.mathangs;
	}

	public void setMathangs(Set<Mathang> mathangs) {
		this.mathangs = mathangs;
	}

}
