package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mathang generated by hbm2java
 */
@Entity
@Table(name = "mathang")
public class Mathang implements java.io.Serializable {

	private Integer mamh;
	private Chatlieu chatlieu;
	private Loaimh loaimh;
	private Nhanhieu nhanhieu;
	private String tenmh;
	private String mota;
	private String trangthai;
	private String cachlam;
	private String phanloai;
	private Set<Hinhanhmh> hinhanhmhs = new HashSet<Hinhanhmh>(0);
	private Set<Gia> gias = new HashSet<Gia>(0);
	private Set<Binhluan> binhluans = new HashSet<Binhluan>(0);
	private Set<CtKhuyenmai> ctKhuyenmais = new HashSet<CtKhuyenmai>(0);
	private Set<CtMathang> ctMathangs = new HashSet<CtMathang>(0);
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);

	public Mathang() {
	}

	public Mathang(Chatlieu chatlieu, Nhanhieu nhanhieu) {
		this.chatlieu = chatlieu;
		this.nhanhieu = nhanhieu;
	}

	public Mathang(Integer mamh) {
		super();
		this.mamh = mamh;
	}

	public Mathang(Chatlieu chatlieu, Loaimh loaimh, Nhanhieu nhanhieu, String tenmh, String mota, String trangthai,
			String cachlam, String phanloai, Set<Hinhanhmh> hinhanhmhs, Set<Gia> gias, Set<Binhluan> binhluans,
			Set<CtKhuyenmai> ctKhuyenmais, Set<CtMathang> ctMathangs, Set<Danhgia> danhgias) {
		this.chatlieu = chatlieu;
		this.loaimh = loaimh;
		this.nhanhieu = nhanhieu;
		this.tenmh = tenmh;
		this.mota = mota;
		this.trangthai = trangthai;
		this.cachlam = cachlam;
		this.phanloai = phanloai;
		this.hinhanhmhs = hinhanhmhs;
		this.gias = gias;
		this.binhluans = binhluans;
		this.ctKhuyenmais = ctKhuyenmais;
		this.ctMathangs = ctMathangs;
		this.danhgias = danhgias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAMH", unique = true, nullable = false)
	public Integer getMamh() {
		return this.mamh;
	}

	public void setMamh(Integer mamh) {
		this.mamh = mamh;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MACL", nullable = false)
	public Chatlieu getChatlieu() {
		return this.chatlieu;
	}

	public void setChatlieu(Chatlieu chatlieu) {
		this.chatlieu = chatlieu;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MALOAIMH")
	public Loaimh getLoaimh() {
		return this.loaimh;
	}

	public void setLoaimh(Loaimh loaimh) {
		this.loaimh = loaimh;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MANH", nullable = false)
	public Nhanhieu getNhanhieu() {
		return this.nhanhieu;
	}

	public void setNhanhieu(Nhanhieu nhanhieu) {
		this.nhanhieu = nhanhieu;
	}

	@Column(name = "TENMH", length = 45)
	public String getTenmh() {
		return this.tenmh;
	}

	public void setTenmh(String tenmh) {
		this.tenmh = tenmh;
	}

	@Column(name = "MOTA", length = 45)
	public String getMota() {
		return this.mota;
	}

	public void setMota(String mota) {
		this.mota = mota;
	}

	@Column(name = "TRANGTHAI", length = 45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "CACHLAM", length = 45)
	public String getCachlam() {
		return this.cachlam;
	}

	public void setCachlam(String cachlam) {
		this.cachlam = cachlam;
	}

	@Column(name = "PHANLOAI", length = 45)
	public String getPhanloai() {
		return this.phanloai;
	}

	public void setPhanloai(String phanloai) {
		this.phanloai = phanloai;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mathang")
	public Set<Hinhanhmh> getHinhanhmhs() {
		return this.hinhanhmhs;
	}

	public void setHinhanhmhs(Set<Hinhanhmh> hinhanhmhs) {
		this.hinhanhmhs = hinhanhmhs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mathang")
	public Set<Gia> getGias() {
		return this.gias;
	}

	public void setGias(Set<Gia> gias) {
		this.gias = gias;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mathang")
	public Set<Binhluan> getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set<Binhluan> binhluans) {
		this.binhluans = binhluans;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mathang")
	public Set<CtKhuyenmai> getCtKhuyenmais() {
		return this.ctKhuyenmais;
	}

	public void setCtKhuyenmais(Set<CtKhuyenmai> ctKhuyenmais) {
		this.ctKhuyenmais = ctKhuyenmais;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mathang")
	public Set<CtMathang> getCtMathangs() {
		return this.ctMathangs;
	}

	public void setCtMathangs(Set<CtMathang> ctMathangs) {
		this.ctMathangs = ctMathangs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mathang")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

}
