package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhacungcap generated by hbm2java
 */
@Entity
@Table(name = "nhacungcap")
public class Nhacungcap implements java.io.Serializable {

	private Integer mancc;
	private String tenncc;
	private String diachi;
	private String sodt;
	private String email;
	private Set<Phieudat> phieudats = new HashSet<Phieudat>(0);

	public Nhacungcap() {
	}

	public Nhacungcap(Integer mancc) {
		super();
		this.mancc = mancc;
	}

	public Nhacungcap(String tenncc, String diachi, String sodt, String email, Set<Phieudat> phieudats) {
		this.tenncc = tenncc;
		this.diachi = diachi;
		this.sodt = sodt;
		this.email = email;
		this.phieudats = phieudats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MANCC", unique = true, nullable = false)
	public Integer getMancc() {
		return this.mancc;
	}

	public void setMancc(Integer mancc) {
		this.mancc = mancc;
	}

	@Column(name = "TENNCC", length = 45)
	public String getTenncc() {
		return this.tenncc;
	}

	public void setTenncc(String tenncc) {
		this.tenncc = tenncc;
	}

	@Column(name = "DIACHI", length = 45)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "SODT", length = 45)
	public String getSodt() {
		return this.sodt;
	}

	public void setSodt(String sodt) {
		this.sodt = sodt;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhacungcap")
	public Set<Phieudat> getPhieudats() {
		return this.phieudats;
	}

	public void setPhieudats(Set<Phieudat> phieudats) {
		this.phieudats = phieudats;
	}

}
