package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Nhanhieu generated by hbm2java
 */
@Entity
@Table(name = "nhanhieu", uniqueConstraints = @UniqueConstraint(columnNames = "TENNH"))
public class Nhanhieu implements java.io.Serializable {

	private Integer manh;
	private String tennh;
	private Set<Mathang> mathangs = new HashSet<Mathang>(0);

	public Nhanhieu() {
	}

	public Nhanhieu(String tennh) {
		this.tennh = tennh;
	}

	public Nhanhieu(String tennh, Set<Mathang> mathangs) {
		this.tennh = tennh;
		this.mathangs = mathangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MANH", unique = true, nullable = false)
	public Integer getManh() {
		return this.manh;
	}

	public void setManh(Integer manh) {
		this.manh = manh;
	}

	@Column(name = "TENNH", unique = true, nullable = false, length = 45)
	public String getTennh() {
		return this.tennh;
	}

	public void setTennh(String tennh) {
		this.tennh = tennh;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "nhanhieu")
	public Set<Mathang> getMathangs() {
		return this.mathangs;
	}

	public void setMathangs(Set<Mathang> mathangs) {
		this.mathangs = mathangs;
	}

}
