package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieudat generated by hbm2java
 */
@Entity
@Table(name = "phieudat")
public class Phieudat implements java.io.Serializable {

	private Integer mapd;
	private Nhacungcap nhacungcap;
	private Nhanvien nhanvien;
	private Date ngaydat;
	private Set<Phieunhap> phieunhaps = new HashSet<Phieunhap>(0);
	private Set<CtPhieudat> ctPhieudats = new HashSet<CtPhieudat>(0);

	public Phieudat() {
	}

	public Phieudat(Integer mapd) {
		super();
		this.mapd = mapd;
	}

	public Phieudat(Nhacungcap nhacungcap, Nhanvien nhanvien, Date ngaydat, Set<Phieunhap> phieunhaps,
			Set<CtPhieudat> ctPhieudats) {
		this.nhacungcap = nhacungcap;
		this.nhanvien = nhanvien;
		this.ngaydat = ngaydat;
		this.phieunhaps = phieunhaps;
		this.ctPhieudats = ctPhieudats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAPD", unique = true, nullable = false)
	public Integer getMapd() {
		return this.mapd;
	}

	public void setMapd(Integer mapd) {
		this.mapd = mapd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANCC")
	public Nhacungcap getNhacungcap() {
		return this.nhacungcap;
	}

	public void setNhacungcap(Nhacungcap nhacungcap) {
		this.nhacungcap = nhacungcap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANV")
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NGAYDAT", length = 10)
	public Date getNgaydat() {
		return this.ngaydat;
	}

	public void setNgaydat(Date ngaydat) {
		this.ngaydat = ngaydat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieudat")
	public Set<Phieunhap> getPhieunhaps() {
		return this.phieunhaps;
	}

	public void setPhieunhaps(Set<Phieunhap> phieunhaps) {
		this.phieunhaps = phieunhaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieudat")
	public Set<CtPhieudat> getCtPhieudats() {
		return this.ctPhieudats;
	}

	public void setCtPhieudats(Set<CtPhieudat> ctPhieudats) {
		this.ctPhieudats = ctPhieudats;
	}

}
