package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Quyen generated by hbm2java
 */
@Entity
@Table(name = "quyen", uniqueConstraints = @UniqueConstraint(columnNames = "TENQUYEN"))
public class Quyen implements java.io.Serializable {

	private Integer maquyen;
	private String tenquyen;
	private Set<CtQuyen> ctQuyens = new HashSet<CtQuyen>(0);

	public Quyen() {
	}

	public Quyen(Integer maquyen) {
		super();
		this.maquyen = maquyen;
	}

	public Quyen(String tenquyen) {
		this.tenquyen = tenquyen;
	}

	public Quyen(String tenquyen, Set<CtQuyen> ctQuyens) {
		this.tenquyen = tenquyen;
		this.ctQuyens = ctQuyens;
	}

	

	public Quyen(Integer maquyen, String tenquyen) {
		super();
		this.maquyen = maquyen;
		this.tenquyen = tenquyen;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAQUYEN", unique = true, nullable = false)
	public Integer getMaquyen() {
		return this.maquyen;
	}

	public void setMaquyen(Integer maquyen) {
		this.maquyen = maquyen;
	}

	@Column(name = "TENQUYEN", unique = true, nullable = false, length = 45)
	public String getTenquyen() {
		return this.tenquyen;
	}

	public void setTenquyen(String tenquyen) {
		this.tenquyen = tenquyen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quyen")
	public Set<CtQuyen> getCtQuyens() {
		return this.ctQuyens;
	}

	public void setCtQuyens(Set<CtQuyen> ctQuyens) {
		this.ctQuyens = ctQuyens;
	}

}
