package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", uniqueConstraints = { @UniqueConstraint(columnNames = "EMAIL"),
		@UniqueConstraint(columnNames = "MAKH"), @UniqueConstraint(columnNames = "MANV") })
public class Taikhoan implements java.io.Serializable {

	private Integer matk;
	private Khachhang khachhang;
	private Nhanvien nhanvien;
	private String email;
	private String matkhau;
	private Set<Binhluan> binhluans = new HashSet<Binhluan>(0);
	private Set<Khachhang> khachhangs = new HashSet<Khachhang>(0);
	private Set<Danhgia> danhgias = new HashSet<Danhgia>(0);
	private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);
	private Set<CtQuyen> ctQuyens = new HashSet<CtQuyen>(0);

	public Taikhoan() {
	}
	
	public Taikhoan(String email, String matkhau) {
		this.email = email;
		this.matkhau=matkhau;
	}

	
	public Taikhoan(Integer matk) {
		super();
		this.matk = matk;
	}

	public Taikhoan(Khachhang khachhang, Nhanvien nhanvien, String email, String matkhau, Set<Binhluan> binhluans,
			Set<Khachhang> khachhangs, Set<Danhgia> danhgias, Set<Nhanvien> nhanviens, Set<CtQuyen> ctQuyens) {
		this.khachhang = khachhang;
		this.nhanvien = nhanvien;
		this.email = email;
		this.matkhau = matkhau;
		this.binhluans = binhluans;
		this.khachhangs = khachhangs;
		this.danhgias = danhgias;
		this.nhanviens = nhanviens;
		this.ctQuyens = ctQuyens;
	}

	public Taikhoan(String string, String string2, String encode) {
		// TODO Auto-generated constructor stub
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MATK", unique = true, nullable = false)
	public Integer getMatk() {
		return this.matk;
	}

	public void setMatk(Integer matk) {
		this.matk = matk;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MAKH", unique = true)
	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MANV", unique = true)
	public Nhanvien getNhanvien() {
		return this.nhanvien;
	}

	public void setNhanvien(Nhanvien nhanvien) {
		this.nhanvien = nhanvien;
	}

	@Column(name = "EMAIL", unique = true, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MATKHAU", length = 45)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "taikhoan")
	public Set<Binhluan> getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set<Binhluan> binhluans) {
		this.binhluans = binhluans;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "taikhoan")
	public Set<Khachhang> getKhachhangs() {
		return this.khachhangs;
	}

	public void setKhachhangs(Set<Khachhang> khachhangs) {
		this.khachhangs = khachhangs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "taikhoan")
	public Set<Danhgia> getDanhgias() {
		return this.danhgias;
	}

	public void setDanhgias(Set<Danhgia> danhgias) {
		this.danhgias = danhgias;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "taikhoan")
	public Set<Nhanvien> getNhanviens() {
		return this.nhanviens;
	}

	public void setNhanviens(Set<Nhanvien> nhanviens) {
		this.nhanviens = nhanviens;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "taikhoan")
	public Set<CtQuyen> getCtQuyens() {
		return this.ctQuyens;
	}

	public void setCtQuyens(Set<CtQuyen> ctQuyens) {
		this.ctQuyens = ctQuyens;
	}
    
}
