package com.example.demo.entity;
// Generated Jul 11, 2023, 9:57:41 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Trangthaihd generated by hbm2java
 */
@Entity
@Table(name = "trangthaihd", uniqueConstraints = @UniqueConstraint(columnNames = "TRANGTHAI"))
public class Trangthaihd implements java.io.Serializable {

	private Integer matthd;
	private String trangthai;
	private Set<CtTrangthai> ctTrangthais = new HashSet<CtTrangthai>(0);

	public Trangthaihd() {
	}

	public Trangthaihd(String trangthai) {
		this.trangthai = trangthai;
	}

	public Trangthaihd(String trangthai, Set<CtTrangthai> ctTrangthais) {
		this.trangthai = trangthai;
		this.ctTrangthais = ctTrangthais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MATTHD", unique = true, nullable = false)
	public Integer getMatthd() {
		return this.matthd;
	}

	public void setMatthd(Integer matthd) {
		this.matthd = matthd;
	}

	@Column(name = "TRANGTHAI", unique = true, nullable = false, length = 45)
	public String getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(String trangthai) {
		this.trangthai = trangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trangthaihd")
	public Set<CtTrangthai> getCtTrangthais() {
		return this.ctTrangthais;
	}

	public void setCtTrangthais(Set<CtTrangthai> ctTrangthais) {
		this.ctTrangthais = ctTrangthais;
	}

}
